### ISSUE TITLE
static folder for image

### ISSUE THREAD

**Issue by limin9988** [react-boilerplate/react-boilerplate#1610] opened 2017-02-23 08:57 UTC
hi, how do i do the static folder for image on development and build?

**Comment by samit4me** [comment] 2017-02-23 10:45
Hi @limin9988, how did you want to use the image? 

## In a component directly:
```jsx
import Banner from './banner.jpg';
...
<img src={Banner} alt="react-boilerplate - Logo" />
```
[Example in `<Header>`](https://github.com/react-boilerplate/react-boilerplate/blob/8407cf05c4f1d43ca6c78625b7b8fee7627fdedb/app/components/Header/index.js#L8)

## Available in the root directory (static file):
```js
import '!file-loader?name=[name].[ext]!./image.png';
```
[Example in `app.js`](https://github.com/react-boilerplate/react-boilerplate/blob/8407cf05c4f1d43ca6c78625b7b8fee7627fdedb/app/app.js#L32)

**Comment by limin9988** [comment] 2017-02-23 10:49
static folder 
something like <img src="image\react-boilerplate-logo.jpg" />

**Comment by samit4me** [comment] 2017-02-23 11:06
I'm not sure what makes it dynamic, but you should be able to alter the previous example to include a path:
```js
import '!file-loader?name=[name].[ext]&outputPath=images/!./image.png';
```
Them you should be able to view this in your browser http://localhost:3000/images/image.png

If that doesn't work in your use case, please take a look at the docs and let us know how you go https://github.com/webpack-contrib/file-loader.

**Comment by limin9988** [comment] 2017-02-23 11:09
thanks

**Comment by samit4me** [comment] 2017-02-23 11:19
Did you get it sorted?

**Comment by gihrig** [comment] 2017-02-24 00:43
@samit4me Do the [docs](https://github.com/react-boilerplate/react-boilerplate/blob/dev/docs/general/gotchas.md#special-images-in-html-files) need to be updated?

**Comment by samit4me** [comment] 2017-02-24 01:36
Didn't know that even existed @gihrig, but maybe. If @limin9988 could share the use case and what worked, we could certainly update the docs to help make this easier.

**Comment by gihrig** [comment] 2017-02-24 01:41
> Didn't know that even existed

Good reason to convert to GitBook as mentioned in #951 😁

**Comment by samit4me** [comment] 2017-02-28 11:02
Closing issue as it appears to be resolved, please feel free to re-open if the problem is not resolved.

**Closed by samit4me** 2017-02-28 11:02 UTC

**Comment by chrismv48** [comment] 2017-09-01 15:29
Not sure if this is still relevant, but I was able to solve this by adding:
`app.use(express.static('public'))` (where public is your static assets directory)
to express (`server/index.js`)

Now I can reference images like so: `<img src="/uploads/character/display_image/1/people.jpeg" height="200">`
