### ISSUE TITLE
NPM run setup not working

### ISSUE THREAD

**Issue by MattGoldwater** [react-boilerplate/react-boilerplate#2603] opened 2019-03-25 17:55 UTC
## Description
An error occurs when trying to install the modules dependencies via the command npm run setup. 

Error: Cannot find module 'compare-versions'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/yh04578/other-repos/react-boilerplate/internals/scripts/setup.js:8:25)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-boilerplate@3.7.0 setup: `node ./internals/scripts/setup.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-boilerplate@3.7.0 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yh04578/.npm/_logs/2019-03-25T17_50_46_300Z-debug.log

## Steps to reproduce
npm run setup

I tried running npm cache clean as suggested here https://github.com/react-boilerplate/react-boilerplate/issues/872 , but I got a message that seemed to apply that won't be the problem for npm versions greater than 5. 

## Versions

- React-Boilerplate: 3.7.0
- Node/NPM: 8.15.1 / 6.4.1

**Comment by julienben** [comment] 2019-03-25 18:20
Hmmm weirdly I can't reproduce but I have an idea of what might be wrong. Can I ask you to run a test?

Steps:
- Delete your `node_modules` folder
- In `package.json`, replace line 29 with `"presetup": "npm i chalk shelljs compare-versions",` (basically adding `compare-versions` to the list of packages that get installed before running the setup script)
- Retry `npm run setup`
- Come back to report success/failure

**Comment by MattGoldwater** [comment] 2019-03-25 18:55
Thanks for trying to help. Unfortunately, it's still not working.

> react-boilerplate@3.7.0 presetup /Users/yh04578/other-repos/react-boilerplate
> npm i chalk shelljs compare-versions

+ compare-versions@3.4.0
+ chalk@2.4.1
+ shelljs@0.8.2
added 24 packages from 14 contributors in 5.826s

> react-boilerplate@3.7.0 setup /Users/yh04578/other-repos/react-boilerplate
> node ./internals/scripts/setup.js



Do you want to clear old repository? [Y/n] n
 Leaving your repository untouched ✓
Installing dependencies.. ✓(This might take a while)

Done!%  

However, it doesn't seem like any more dependencies are being installed. I also answered yes to this question and it didn't seem to change the result. 

As a result, upon starting the repo I get

npm start

> react-boilerplate@3.7.0 start /Users/yh04578/other-repos/react-boilerplate
> cross-env NODE_ENV=development node server

sh: cross-env: command not found

**Comment by julienben** [comment] 2019-03-25 19:09
IMO this issue would have been reported already if it were present for every user... So perhaps this has something to do with your node/npm setup?

What does it look like exactly when you run `setup` after a cloning the repo? This is what I get:

![image](https://user-images.githubusercontent.com/8948127/54947024-06153600-4f42-11e9-9e40-553f7ab888c3.png)
![image](https://user-images.githubusercontent.com/8948127/54947105-33fa7a80-4f42-11e9-8c5e-b84143b4c82d.png)

**Comment by julienben** [comment] 2019-03-25 19:10
(Everything works if I `npm start` afterwards.)

**Comment by MattGoldwater** [comment] 2019-03-25 20:59
Yeah I wouldn't be surprised if it's something with my computer. Here is my full log for the two times I ran npm run setup after changing line 29 to "presetup": "npm i chalk shelljs compare-versions". I deleted and recloned the repo before doing npm run setup the second time.

When I selected yes to Do you want to clear old repository?

➜  react-boilerplate git:(master) ✗ npm run setup

> react-boilerplate@3.7.0 presetup /Users/yh04578/other-repos/react-boilerplate
> npm i chalk shelljs compare-versions

+ shelljs@0.8.3
+ chalk@2.4.2
+ compare-versions@3.4.0
added 24 packages from 14 contributors in 7.152s

> react-boilerplate@3.7.0 setup /Users/yh04578/other-repos/react-boilerplate
> node ./internals/scripts/setup.js



Do you want to clear old repository? [Y/n] Y
Removing old repository ✓
Installing dependencies.. ✓(This might take a while)

Initialising new repository
Done!%    

When I selected no to Do you want to clear old repository?

react-boilerplate git:(master) npm run setup

> react-boilerplate@3.7.0 presetup /Users/yh04578/other-repos/react-boilerplate
> npm i chalk shelljs compare-versions

+ compare-versions@3.4.0
+ chalk@2.4.1
+ shelljs@0.8.2
added 24 packages from 14 contributors in 5.826s

> react-boilerplate@3.7.0 setup /Users/yh04578/other-repos/react-boilerplate
> node ./internals/scripts/setup.js



Do you want to clear old repository? [Y/n] n
 Leaving your repository untouched ✓
Installing dependencies.. ✓(This might take a while)


Done!%

**Comment by julienben** [comment] 2019-03-26 10:07
A screenshot of what you see in the console would be more helpful...

**Comment by JoshuaLamusga** [comment] 2019-03-29 13:59
Hey, npm run setup fails for me entirely with _missing script: setup_. Following README exactly, very little room for interpretation. Git clone works, npm run setup fails.

I don't think this builds for anyone. If it does, you're running extra commands. Please enlighten.

**Comment by mafideju** [comment] 2019-05-05 02:20
Same happened here. Had to run the good old npm install instead of the recomended command.

**Comment by julienben** [comment] 2019-05-05 07:35
Can you share details on your environment and screenshots of your console when you try to run the setup script?

We can't help with an issue that we can't reproduce or diagnose.

**Comment by mafideju** [comment] 2019-05-05 13:14
I do not have an issue. 
Has solved this issue running npm install.

At home using Ubuntu, at work using Windows 10. Is not a problem with machines, the problem is in the boiler.

Screenshots you ask for are in the top of this thread. Back and look it, don't need to repost it again. They are there and they are clear. 

Npm run setup is broken. It's not working properly. The console is telling you to install packages manually. I installed 'compare-versions' then had to install express. So realized that need to INSTALL every pack one by one. Running npm install things started to work fine.

Check in the place where this command is mounted. 

You don't need another screenshot. Just a moment of good will.

**Comment by julienben** [comment] 2019-05-05 13:43
> Screenshots you ask for are in the top of this thread. Back and look it, don't need to repost it again. They are there and they are clear.

The only screenshots in this thread are mine. When I run the script locally on my computer, I get no issues.

> Npm run setup is broken. It's not working properly. The console is telling you to install packages manually. I installed 'compare-versions' then had to install express. So realized that need to INSTALL every pack one by one. Running npm install things started to work fine.

I'm aware that some people are having issues with the setup script. I do need your help to understand what the problem is exactly because, again, the script works perfectly fine on my computer.

> You don't need another screenshot. Just a moment of good will.

Your tone is condescending and entitled and I suggest you rethink it before replying here (or anywhere else on Github for that matter).

Since you don't seem to be aware, you should know that contributors to this project aren't paid for their work and some of us have donated hundreds of hours of personal time to it.

If you use this project and have either learned or gained any amount of productivity from it, the debt is yours my friend. You owe it to us to help us fix any issues you find.

**Comment by gretzky** [comment] 2019-05-05 13:54
@mafideju We cannot help fix this issue unless we know exactly what’s going on. I understand it’s frustrating when things don’t work as advertised— but remember that @julienben and I devote our free time and energy to maintaining this project for free. We aren’t contractors, we aren’t paid, and we can’t automatically know how to fix everything that happens on every particular machine. Your response is really rude and I hope you can understand that type of response isn’t going to get any further help or persistence on our part.

**Comment by mafideju** [comment] 2019-05-05 14:26
You don't know how to read English. That is it.
I solved an issue that you lazy guys tried to push ahead. 
Devote your time to do meaningful things, not to be a lazy asshole.

**Comment by julienben** [comment] 2019-05-05 14:32
I've locked this conversation as we have a troll on our hands (that or the most entitled douchebag to ever sign up for a Github account).

@mafideju You've been reported. You're no longer welcome to comment anywhere in this project.

**Comment by julienben** [comment] 2019-06-03 09:43
This thread is compromised so I'm closing but please consider reopening. I'm still very much interested in fixing this issue but will need help. At least detailed console screenshots as a first step.

**Closed by julienben** 2019-06-03 09:43 UTC
