### ISSUE TITLE
best place for firebase-messaging-sw.js 

### ISSUE THREAD

**Issue by smemamian** [react-boilerplate/react-boilerplate#2533] opened 2019-01-06 10:12 UTC
## Description
I want to use firebase. I should use `firebase-messaging-sw.js` as a static file but I don't know where I place this file.  because I got this error:

`FirebaseError {code: "messaging/failed-serviceworker-registration", message: "Messaging: We are unable to register the default s…). (messaging/failed-serviceworker-registration).", browserErrorMessage: "Failed to register a ServiceWorker: The script has an unsupported MIME type ('text/html').", stack: "FirebaseError: Messaging: We are unable to registe…es/@firebase/messaging/dist/index.cjs.js:1951:32)"}`

## Steps to reproduce

**Expected behavior**

**Screenshots**

## Versions

- React-Boilerplate: 3.7.0
- Node/NPM: v8.10.0
- Browser: chrome

**Comment by julienben** [comment] 2019-01-06 10:15
Closing because:
1- Not an issue with the boilerplate
2- No steps to reproduce
3- No idea what the issue is anyway

**Closed by julienben** 2019-01-06 10:15 UTC

**Comment by smemamian** [comment] 2019-01-06 11:37
I added like them:

    new OfflinePlugin({
      relativePaths: false,
      publicPath: '/',
      appShell: '/',
      ServiceWorker: {
        events: true,
        entry: path.join(process.cwd(), 'app/firebase-messaging-sw.js') //<-- path for your extended service worker
      },

      // No need to cache .htaccess. See http://mxs.is/googmp,
      // this is applied before any match in `caches` section
      excludes: ['.htaccess'],

I have a `push-notification.js` and I should call `firebase-messaging-sw.js` inside it:

```
  navigator.serviceWorker
    .register('./firebase-messaging-sw.js')
    .then((registration) => {
      firebase.messaging().useServiceWorker(registration);
    });
```

two files are the same directory(app).
but I got the same error.
also `http://localhost:3000/firebase-messaging-sw.js` show a `page not found`

**Comment by smemamian** [comment] 2019-01-06 11:53
solved:
1.@joshuaalpuerto 
 2. you should import it like this:

app.js
`import 'file-loader?name=firebase-messaging-sw.js!./firebase-messaging-sw.js';`
