### ISSUE TITLE
When doing `npm install`, the uninstall process is invoked, then all modules are deleted

### ISSUE THREAD

**Issue by marsonmao** [react-boilerplate/react-boilerplate#1814] opened 2017-06-20 07:15 UTC
## Description

When I tried to `npm install material-ui`, the uninstall process is invoked and then I lost all node modules, why is this happening?

Please see the following log:

> C:\project\react-boilerplate>npm install material-ui
> 
> \> pre-commit@1.1.3 uninstall C:\project\react-boilerplate\node_modules\pre-commit
> \> node uninstall.js
> 
> npm WARN gentlyRm not removing C:\project\react-boilerplate\node_modules\acorn-globals\node_modules\.bin\acorn.cmd as it wasn't installed by C:\project\react-boilerplate\node_modules\acorn-globals\node_modules\acorn
> npm WARN gentlyRm not removing C:\project\react-boilerplate\node_modules\acorn-globals\node_modules\.bin\acorn as it wasn't installed by C:\project\react-boilerplate\node_modules\acorn-globals\node_modules\acorn
> npm WARN material-ui@0.18.3 requires a peer of react@^15.4.0 but none was installed.
> npm WARN material-ui@0.18.3 requires a peer of react-dom@^15.4.0 but none was installed.
> npm WARN material-ui@0.18.3 requires a peer of react-tap-event-plugin@^2.0.1 but none was installed.
> npm WARN react-transition-group@1.2.0 requires a peer of react@^15.0.0 but none was installed.
> npm WARN react-transition-group@1.2.0 requires a peer of react-dom@^15.0.0 but none was installed.
> npm WARN recompose@0.23.4 requires a peer of react@^0.14.0 || ^15.0.0 but none was installed.
> npm WARN react-event-listener@0.4.5 requires a peer of react@^0.14.0 || ^15.0.0 but none was installed.
> 
> + material-ui@0.18.3
> added 15 packages, removed 1163 packages and updated 47 packages in 33.132s

# Versions

- React-Boilerplate "version": "3.4.0",

> C:\project\react-boilerplate>npm -v
> 5.0.3
> C:\project\react-boilerplate>node -v
> v8.1.2
> C:\project\react-boilerplate>yarn -v
> yarn install v0.24.6

...And yarn fixes my missing modules by this command, though I was just trying to see the version of yarn. Still, I'd like to know what triggered the uninstall process, otherwise I keep losing modules with every `npm install`.

# Just for reference
The log of yarn fixing modules:

> $ npm run npmcheckversion
> 
> > react-boilerplate@3.4.0 npmcheckversion C:\d8\project\react-boilerplate
> > node ./internals/scripts/npmcheckversion.js
> 
> [1/4] Resolving packages...
> [2/4] Fetching packages...
> warning fsevents@1.0.15: The platform "win32" is incompatible with this module.
> info "fsevents@1.0.15" is an optional dependency and failed compatibility check. Excluding it from installation.
> [3/4] Linking dependencies...
> warning "eslint-import-resolver-webpack@0.8.0" has incorrect peer dependency "webpack@^1.11.0 || ^2.1.0-beta || ^2.1.0".
> warning "html-webpack-plugin@2.24.1" has incorrect peer dependency "webpack@1 || ^2.1.0-beta".
> warning "material-ui@0.18.3" has unmet peer dependency "react-tap-event-plugin@^2.0.1".
> [4/4] Building fresh packages...
> success Saved lockfile.
> $ npm run build:dll
> 
> > react-boilerplate@3.4.0 build:dll C:\d8\project\react-boilerplate
> > node ./internals/scripts/dependencies.js
> 
> Building the Webpack DLL...
> Hash: e1798f3d015c7553b0d0
> Version: webpack 2.2.0-rc.3
> Time: 7445ms
>                       Asset     Size  Chunks                    Chunk Names
> reactBoilerplateDeps.dll.js  4.54 MB       0  [emitted]  [big]  reactBoilerplateDeps
> chunk    {0} reactBoilerplateDeps.dll.js (reactBoilerplateDeps) 3.76 MB [entry] [rendered]
>  [./node_modules/babel-polyfill/lib/index.js] ./~/babel-polyfill/lib/index.js 833 bytes {0} [built]
>  [./node_modules/core-js/index.js] ./~/core-js/index.js 639 bytes {0} [built]
>  [./node_modules/react-redux/lib/index.js] ./~/react-redux/lib/index.js 475 bytes {0} [built]
>  [./node_modules/react-router-redux/lib/index.js] ./~/react-router-redux/lib/index.js 1.97 kB {0} [built]
>  [./node_modules/react-router-scroll/lib/index.js] ./~/react-router-scroll/lib/index.js 512 bytes {0} [built]
>  [./node_modules/react-router/es/index.js] ./~/react-router/es/index.js 1.46 kB {0} [built]
>  [./node_modules/react/react.js] ./~/react/react.js 56 bytes {0} [built]
>  [./node_modules/redux-immutable/dist/index.js] ./~/redux-immutable/dist/index.js 390 bytes {0} [built]
>  [./node_modules/redux-saga/es/index.js] ./~/redux-saga/es/index.js 457 bytes {0} [built]
>     [2] dll reactBoilerplateDeps 12 bytes {0} [built]
>  [./node_modules/redux/es/index.js] ./~/redux/es/index.js 1.08 kB {0} [built]
>  [./node_modules/reselect/es/index.js] ./~/reselect/es/index.js 3.63 kB {0} [built]
>  [./node_modules/styled-components/dist/styled-components.es.js] ./~/styled-components/dist/styled-components.es.js 230 kB {0} [built]
>  [./node_modules/warning/browser.js] ./~/warning/browser.js 1.81 kB {0} [built]
>  [./node_modules/whatwg-fetch/fetch.js] ./~/whatwg-fetch/fetch.js 12.5 kB {0} [built]
>      + 1017 hidden modules
> Done in 65.54s.

**Comment by marsonmao** [comment] 2017-06-21 02:13
No one else encounter this problem?

**Comment by alexvandervegt** [comment] 2017-06-21 05:45
Yes i have this to. I use yarn now

**Comment by marsonmao** [comment] 2017-06-21 05:52
@alexvandervegt thanks for replying. So I think this is kind of a bug? Some kind of inconsistency with the latest `npm`? Should it be fixed?

**Comment by alexvandervegt** [comment] 2017-06-21 06:00
Nope its a command which is triggered in the package.json

But you can use yarn to install updates without a problem.

**Comment by marsonmao** [comment] 2017-06-21 06:07
I think I'll use yarn instead of npm. But shouldn't npm to be working fine as well? 

By "bug" I mean the "uninstall" command should not be triggered by a "npm install", which doesn't make sense.

**Comment by Dattaya** [comment] 2017-06-21 19:39
@marsonmao, that definitely sounds like a bug, but I couldn't reproduce (I try everything on the dev branch)

**Comment by marsonmao** [comment] 2017-06-22 01:27
I haven't got this issue before I upgraded to node 8 and npm 5, I guess it's due to these new versions.

Could you give me some hint how `pre-commit`'s `uninstall.js` is being invoked right now? I can try to trace the cause.

**Comment by Targma** [comment] 2017-06-22 15:30
Had same issue i used node v8.1.2 (current one) cloned repo 
"npm install -g yarn"
"npm run setup"
"npm run start" (after i got good look around i stopped copied it in another dir for reference)
"npm run clean"
"npm run start"

New cmd shell.
"npm install --save react-bootstrap"
and it uninstalled around most of packages and installing bootstrap but leaving it in nonfunctional state.

**Comment by gihrig** [comment] 2017-06-22 17:45
I have had a very successful install of many Node versions [(with tj/n)](https://github.com/tj/n). Installing npm v5 totally broke this setup (having nothing to do with RBP).

tj/n has an [npm update script](https://github.com/tj/n#working-with-npm) that installs the latest version of npm for all locally available versions of Node. This script reports success, but fails to install npm 5.

In my experience, npm 5 represents a [major breaking change](http://blog.npmjs.org/post/161081169345/v500) from earlier versions. 

While npm 5 is included with [latest Node](https://nodejs.org/en/download/releases/), getting it to work with existing systems (e.g. RBP) appears to be a challenge.

**Comment by Dattaya** [comment] 2017-06-22 19:09
> Could you give me some hint how pre-commit's uninstall.js is being invoked right now

We don't call it manually, that's how `pre-commit` works (look at their `package.json`, `uninstall` script), as @gihrig said, npm 5 has some breaking changes and also a bunch of bugs: https://github.com/npm/npm/issues?q=is%3Aissue+is%3Aopen+label%3Anpm5

**Comment by Dattaya** [comment] 2017-06-22 20:42
btw, it's not just RB, take a look at https://github.com/npm/npm/issues/17379 

> added 1 package and removed 643 packages in 9.524s

smart thinking, `npm`, why do you need so many packages, one should be clearly enough 😄

**Comment by gihrig** [comment] 2017-06-22 20:48
Captain Obvious here, but "fixing" RBP is clear not the right thing. 😁 

Closing as not an RBP issue. Feel free to discuss...

**Closed by gihrig** 2017-06-22 20:48 UTC
Labels: unconfirmed-bug

**Comment by marsonmao** [comment] 2017-06-26 01:47
Ok, so for anyone that getting this `uninstall` issue, just install packages by `yarn` instead of latest `npm`.

**Comment by manuepeva** [comment] 2017-09-28 17:38
I have something similar to this, in my case, the solution was to use Yarn package manager and "upgrade" the typescript compiler (tsc) using this tool.

**Comment by Se0ng11** [comment] 2018-04-20 07:32
same here, using node v8.11.1 and when running 
npm install --save reactstrap@next react react-dom
it delete all the node_modules item
