### ISSUE TITLE
Debugging npm run build error

### ISSUE THREAD

**Issue by Altiano** [react-boilerplate/react-boilerplate#1529] opened 2017-01-27 13:49 UTC
To make things faster I rewrite npm run build command to `webpack --config internals/webpack/webpack.prod.babel.js --color -p --display-error-details --progress` with added display-error-details so I can see the errors 
But to no good, I can't debug what causing the build to failed.
This is the result
![image](https://cloud.githubusercontent.com/assets/8316282/22372893/2fd86554-e4da-11e6-8137-28d6c5c1af1c.png)

The build folder is created, at first the app can be open but after navigating to other route, console print an error: 
![image](https://cloud.githubusercontent.com/assets/8316282/22372939/6f83c3e2-e4da-11e6-9ad9-fa1e9b8e533a.png)

This is only failed on linux machine but on windows it is not
I think I'm using v3.2.1 of this boilerpate (I'm not sure where to look)
Is there any advice you could give?

**Comment by gihrig** [comment] 2017-01-27 20:12
> I think I'm using v3.2.1 of this boilerpate (I'm not sure where to look)

Look in `package.json` line 3

Many strange errors are caused by transient dependency issues.

Try:
`rm -rf node_modules`
`npm cache clean`
`npm install` (`better yarn install` if your version has a `yarn.lock` file)

If that doesn't help, taking a hint from #859 (which is about Docker, but still running on Linux)

> you might need to install libpng12-0

Finally, `pngquant` has appeared in several issues, if you're still having trouble, try searching issues for `is:issue pngquant`.

**Comment by Altiano** [comment] 2017-01-28 02:36
OMG it works.. 👍 💯 🥇 
Thank you so much

**Comment by gihrig** [comment] 2017-01-28 03:11
@Altiano Great news 🎉 

Which step got things working for you?

**Comment by KarandikarMihir** [comment] 2017-01-28 03:39
@gihrig This is ones of those recurring issues. Let's add these simple steps in the docs?

**Comment by gihrig** [comment] 2017-01-28 03:57
@KarandikarMihir I was thinking of adding to [gotchas.md](https://github.com/react-boilerplate/react-boilerplate/blob/master/docs/general/gotchas.md) See #1491, but this install issue, often solved as suggested here, should be in the `Quick Start` section of `README.md` as well as `gotchas.md`. It sort of is, but I think yarn has sufficiently proved itself that Quick Start should emphasize that `yarn install` is recommended over `npm install`. Also see #760.

**Comment by Altiano** [comment] 2017-01-28 04:00
@gihrig 
`rm -rf node_modules` + `rm -rf build`
`npm cache clean`
`npm install`

**Comment by KarandikarMihir** [comment] 2017-01-28 04:19
@gihrig Ah! I said the same thing in one of the issues. I was just going by the order of notifications 😅 
#1351 #1491 #1529 and many other issues are kind of dups. I'll create a separate issues for this.

**Comment by samit4me** [comment] 2017-02-07 08:45
This one seems to be resolved 🎉 Nice work! Any objections to closing???

**Comment by Altiano** [comment] 2017-02-08 15:09
Another thing may I add..
You need also make sure resolved the UNMET dependencies if there is any.
Like `react-addons-test-utils` to match `react` and `react-dom` (This was also the case why I got errors)

**Comment by gihrig** [comment] 2017-02-09 00:40
@Altiano I've been doing the dependency updates for a while now. The problem with `react-addons-test-utils`, not matching `react` and `react-dom` was an unexpected change made by the React team that caught us unaware. Which is to say the problem did not happen in any version of RBP at the time we released it. I do a fairly thorough manual testing with each dependency update (see: #1561) and this set of dependencies is recorded in `yarn.lock`. The best way you can ensure that you are not affected by random dependency version changes is to use `yarn install` in place of `npm install`.

That being said, `yarn` is still not perfect and I expect there will be issues in future, that's just the nature of the `npm` ecosystem.

As the original issue has been resolved, I'll close this now, but please feel free to open a new issue if you think there are better ways of managing dependencies.

**Closed by gihrig** 2017-02-09 00:40 UTC
Labels: waiting-for-response
