### ISSUE TITLE
Help in debugging react-boilerplate code

### ISSUE THREAD

**Issue by vishalvijay** [react-boilerplate/react-boilerplate#1543] opened 2017-01-30 19:36 UTC
Hi

From past fews days I'm trying react boilerplate. Great project guys \m/

I use to debug my JS application using `debugger` keyword or putting breakpoint in browser console. But with this approach I'm having real pain in debugging react boilerplate code.

- What is the recommended way of debugging this app?
- How do I do it?

**Comment by samit4me** [comment] 2017-01-31 07:49
@Virsaviya 
Thank you for raising an issue, I too get similar problems.

Could you please try changing [Line 55 in internals/webpack/webpack.dev.babel.js](https://github.com/react-boilerplate/react-boilerplate/blob/master/internals/webpack/webpack.dev.babel.js#L55)
from: `devtool: 'cheap-module-eval-source-map',` 
to: `devtool: 'eval-source-map',`. 

Then make sure you stop any currently running npm scripts and then run `npm start`.

I have not yet tried this with webpack v2, but it seems to work with webpack v1. Keen to hear how that goes!

**Comment by vishalvijay** [comment] 2017-01-31 17:49
Thanks @samit4me 

Debugging is working with that change.

Should I raise a PR for the same?

**Comment by samit4me** [comment] 2017-01-31 21:20
Yeah that would be great. Before you do tho, please take a look at the [Webpack Devtool Docs](https://webpack.js.org/configuration/devtool/) to get a feel for your options and also the [CONTRIBUTING guide](https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md) for this repo to get familiar with the process. Thank you for you help, it certainly makes life easier when you can debug hey :smile:

**Comment by gihrig** [comment] 2017-01-31 23:18
Please don't open a PR changing `devtool: 'cheap-module-eval-source-map',` This is used by design to save dev build time see #1087.

However: a PR documenting this would be most welcome. An addition to [`docs/general/faq.md`](https://github.com/react-boilerplate/react-boilerplate/blob/master/docs/general/faq.md) would be most appreciated. 😄 

Here's a list of [build tool options](https://webpack.github.io/docs/configuration.html#devtool) for refernence.

**Comment by samit4me** [comment] 2017-02-01 11:10
It looks like #1087 was mostly referring to `inline-source-map` and above was referring to `eval-source-map`. According to the [docs](https://webpack.js.org/configuration/devtool/#for-development) it seems `cheap-module-eval-source-map` is the same as `eval-source-map`, but
> It is "cheap" because it doesn't have column mappings, it only maps line numbers.

As an experiment, I checked out a fresh copy of master and tried both `cheap-module-eval-source-map` and `eval-source-map` and ran each of the below tests 10x per source map type:

### Initial builds (`npm start`)
~3700ms `cheap-module-eval-source-map` 
~4300ms `eval-source-map`

### Rebuilds (code changes)
~300ms `cheap-module-eval-source-map` 
~300ms `eval-source-map`

Not sure if there are any other things to be aware of but for me, half a second on initial build is a small price to pay to have `debugger` and break points working.

Maybe we could switch to `eval-source-map` for now and when / if the **"Source Maps don't work on Chrome"** problem is fixed we could then switch back to `cheap-module-eval-source-map`.

Thoughts?

**Comment by KarandikarMihir** [comment] 2017-02-01 12:11
@samit4me Those numbers really make the picture more clear. I agree.

**Comment by gihrig** [comment] 2017-02-01 20:02
@samit4me I agree, 600ms for initial build is trivial when compared to the benefit.

Thanks for doing those tests and putting the discussion in context.

**Comment by gihrig** [comment] 2017-02-16 07:21
Resolved in #1559

**Closed by gihrig** 2017-02-16 07:21 UTC
Labels: PR welcome

**Comment by auchenberg** [comment] 2017-03-06 20:11
Did this land? I don't see the source map config changed to `eval-source-map`? https://github.com/react-boilerplate/react-boilerplate/blob/master/internals/webpack/webpack.dev.babel.js#L55

**Comment by samit4me** [comment] 2017-03-06 20:28
It has been merged into the `dev` branch but not yet officially released. It should be in with the next release, not sure when that would be, but looking at release history, it should be within the next month or two.

**Comment by auchenberg** [comment] 2017-03-06 20:29
Cool @samit4me!
