### ISSUE TITLE
useInjectReducer makes Redux action inside useEffect doesn't run

### ISSUE THREAD

**Issue by piavgh** [react-boilerplate/react-boilerplate#2708] opened 2019-08-06 07:33 UTC
Before opening a new issue, please take a moment to review our [**community guidelines**](https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md) to make the contribution process easy and effective for everyone involved.

## Description
This is my sample component:

```
export function CommentPage(props) {
  useInjectReducer({ key, reducer })
  useInjectSaga({ key, saga })

  const { match } = props

  useEffect(() => {
    const params = {
      userId: match.params.userId,
      ruleId: match.params.ruleId,
      formEditId: match.params.formEditId,
      submissionId: match.params.submissionId,
      step: match.params.step,
      respondentEmail: match.params.respondentEmail,
    }

    props.saveParams(params)
  }, [])

  return (
    ...
  )
}
```

Basically, `saveParams` is a Redux action that saves some parameters from the url into Redux store.

If I write the code this way (useInjectReducer above useEffect), when I reloaded the page and check Redux tab in Chrome DevTools, I can see that my action is fired, but immediately after that it was removed from the stack, and Redux store is back to the initial state

I think it might be related to this issue somehow https://github.com/react-boilerplate/react-boilerplate/issues/2680

I found out that if I switch the order of code a bit, it works as expected (I just moved the useInjectReducer below useEffect):

```
export function CommentPage(props) {
  const { match } = props

  useEffect(() => {
    const params = {
      userId: match.params.userId,
      ruleId: match.params.ruleId,
      formEditId: match.params.formEditId,
      submissionId: match.params.submissionId,
      step: match.params.step,
      respondentEmail: match.params.respondentEmail,
    }

    props.saveParams(params)
  }, [])

  useInjectReducer({ key, reducer })
  useInjectSaga({ key, saga })

  return (
    ...
  )
}
```

## Steps to reproduce
Please check this repository: https://github.com/piavgh/react-boilerplate-bug/

File: https://github.com/piavgh/react-boilerplate-bug/blob/master/app/containers/CommentPage/index.js#L37

Run this repository and try to reload the URL: http://localhost:3000/comment/abc/qwe/xyz/sad/1/agt@gmail.com

(Add link to a demo on https://jsfiddle.net or similar if possible)

**Expected behavior**
My Redux action should be fired normally and Redux store should have my correct state

**Screenshots**

Case 1: useInjectReducer above useEffect
https://prnt.sc/oox63l

Case 2: useInjectReducer is below useEffect
https://prnt.sc/oox5cs

## Versions

- React-Boilerplate: 4.0.0
- Node/NPM: v10.15.3
- Browser: Chrome 75

**Comment by julienben** [comment] 2019-08-06 08:51
Hey @piavgh,

Thanks for the detailed bug report! This is indeed a strange issue. This isn't an uncommon pattern and I'm surprised we haven't seen this pop up. I'm on holiday right now but will look into it soon. (Unless someone else gets to it before me?)

If you want to try an alternative which might maybe potentially fix your issue, check out the open PR for v4.1 which uses react-redux's hooks API.

**Comment by piavgh** [comment] 2019-08-13 03:26
Thanks, @julienben 

If I delete `useInjectReducer({ key, reducer })` and move all reducer logic to AppReducer (globalReducer), the code also works properly.

So I think it's somehow related to react-redux (current version is 7.0.2) and in 7.1 they have support for Hooks.

> If you want to try an alternative which might maybe potentially fix your issue, check out the open PR for v4.1 which uses react-redux's hooks API.

How can I use this PR code without breaking my project?

Thank you.

**Comment by piavgh** [comment] 2019-08-13 06:36
@julienben I cloned a new react-boilerplate project, switched to `dev` branch (that contains your PR), and this bug is not fixed.

The behavior is exactly the same as before:

> when I reloaded the page and check Redux tab in Chrome DevTools, I can see that my action is fired, but immediately after that it was removed from the stack, and Redux store is back to the initial state

**Comment by UrosNikolic** [comment] 2019-08-22 00:14
@julienben any update for this bug?

**Comment by Statfine** [comment] 2019-08-22 14:40
how about change useInjectReducer to injectReducer @piavgh

**Comment by julienben** [comment] 2019-08-22 16:35
So... I'm really really sorry but I can't reproduce this :(

![image](https://user-images.githubusercontent.com/8948127/63532655-cadc5a80-c513-11e9-937b-5d294421b1e2.png)

The redux action stays in the stack and the store contains all the expected data.

**Comment by julienben** [comment] 2019-08-22 16:42
Ok after refreshing a dozen times I saw it happening. But after that I clicked the Approve button (which dispatches an action too) and the SAVE_PARAMS action reappeared in the stack along with the expected store changes.

![image](https://user-images.githubusercontent.com/8948127/63533033-a8970c80-c514-11e9-8eee-f20873837910.png)

I think that *maybe* this is just an issue with the Redux dev tools (or a timing/communication issue between the dev tools and react-boilerplate).

The first reason is that I truly don't see how we could be "removing" an action that's already been dispatched.

The second reason is that the action reappeared immediately when I clicked Approve so it was never truly lost, it just wasn't being shown in the dev tools.

Can you try clicking Approve on your end and see what happens?

**Comment by piavgh** [comment] 2019-08-23 01:16
@julienben : I confirm that after clicking Approve button, the SAVE_PARAMS action appears again.

And only then the Redux store contains the correct values (instead of null)

So maybe this issue should be posted in Redux repo.

But can you try doing this:

> I found out that if I switch the order of code a bit, it works as expected (I just moved the useInjectReducer below useEffect):

Just change the order of code solves this problem

**Comment by julienben** [comment] 2019-08-29 16:00
Hmmm I think maybe it could be relevant to the redux-devtools repo?

Either way, closing here as it doesn't seem to me like a bug in the boilerplate.

**Closed as completed by julienben** 2019-08-29 16:00 UTC
