### ISSUE TITLE
Immutable.js is not a general purpose solution

### ISSUE THREAD

**Issue by kof** [react-boilerplate/react-boilerplate#441] opened 2016-06-01 08:34 UTC
It has it's benefits in mutations intensive use cases. It allows us to mutate objects faster than copying props and adding new.  Shallow equal on other hand is very fast, as you never have a huge amount of props per component, it is in micro seconds area, so there is not much benefit in regards of rendering.

The benefit of shallowEqual is a standard js objects and libs like lodash. ES2015 allows us to clone objects nicely `nextObj = {...prevObj, prop: 1}` there is not much mental overhead for writing in immutable style without using any library for that.

**Comment by smashercosmo** [comment] 2016-06-01 09:45
I agree, but it is also important to guard yourself from accidental mutation. So, if no library is used to provide immutability, the you need at least deep freeze your state in dev mode.

**Comment by kof** [comment] 2016-06-01 09:51
https://www.npmjs.com/package/redux-freeze

**Comment by SilentCicero** [comment] 2016-06-01 12:32
@kof @mxstbr maybe this middleware makes sense for extra protection. But I like the approach of just using immutable everywhere. Seems like a mature solution.

**Comment by Kielan** [comment] 2016-06-02 08:13
@SilentCicero I like the Select/Reselect pattern as well, allowing every stateful component to be served by a provider through ImmutableJS. 

I agree @kof es2015 syntax is cleaner, but you don't necessarily need to use immutable JS in this boilerplate either.

**Comment by tsm91** [comment] 2016-06-02 09:08
@Kielan actually i replaced all `immutable.js` solution to simple native js and lodash stuff, it wasn't that hard at all

It would be the best to make a script that replaces immutable.js with the native / lodash approach, so if you are not familiar with immutable you do smth like `npm run clean:immutable`

p.s: @kof thanks for `redux-freeze`

**Comment by kof** [comment] 2016-06-02 09:09
The question here is whether immutable.js should be the default. Of course we can add and remove stuff any time.

**Comment by tsm91** [comment] 2016-06-02 09:54
Ahh, right.

I would say to make a more general solution as default.

**Comment by mxstbr** [comment] 2016-06-06 18:16
What about using [`redux-immutable-state-invariant`](https://github.com/leoasis/redux-immutable-state-invariant) to enforce immutable Redux state and getting rid of ImmutableJS?

**Comment by tsm91** [comment] 2016-06-06 21:17
ok, so there is

 * https://github.com/buunguyen/redux-freeze
 * https://github.com/leoasis/redux-immutable-state-invariant

i think we should choose [redux-freeze](https://github.com/buunguyen/redux-freeze/blob/master/src/middleware.js) because it is very lean and simple (15 sloc)

cc @kof @mxstbr

**Comment by kof** [comment] 2016-06-08 10:06
Exact answer to this issue https://youtu.be/5pMDd1t2thc?t=2509

**Comment by gihrig** [comment] 2016-06-13 18:52
I particularly like the the [redux-freeze](https://github.com/buunguyen/redux-freeze) approach for its dev-only footprint and avoidance of [immutable's](https://github.com/facebook/immutable-js) special syntax.

**Comment by tzarger** [comment] 2016-06-21 17:49
+1 https://github.com/buunguyen/redux-freeze

**Comment by SimonSelg** [comment] 2016-06-23 16:15
+1 for the redux-freeze  approach from me too.

**Comment by FezVrasta** [comment] 2016-06-27 11:22
What about Crio? https://github.com/planttheidea/crio

**Comment by mxstbr** [comment] 2016-06-27 11:25
> redux-freeze seems like an additional protection layer that can't and doesn't want to replace immutable libraries.

Isn't that a better approach though? Not sure having an immutable library gives us much more benefits, it only adds a lot more complexity.

**Comment by smashercosmo** [comment] 2016-06-27 11:29
@FezVrasta We moved from ImmutableJS to seamless-immutable, but now considering using plain js structures (+lodash) and redux-freeze. Not because there is something bad with both libraries, but we just can't see the value, that they bring to us.

**Comment by FezVrasta** [comment] 2016-06-27 11:30
@mxstbr Without an immutation library, the cost of the comparisons between objects it's the same as plain js, so you don't address the performance problems.

**Comment by mxstbr** [comment] 2016-06-27 11:44
> @mxstbr Without an immutation library, the cost of the comparisons between objects it's the same as plain js, so you don't address the performance problems.

Ah yeah true, good point. The whole idea behind using `ImmutableJS` in this boilerplate was:

```JS
shouldComponentUpdate(nextProps) {
  return !this.props.equals(nextProps);
}
```

`redux-freeze` doesn't really solve that, does it?

**Comment by FezVrasta** [comment] 2016-06-27 11:47
For what I understood, it doesn't. Otherwise they wouldn't advise to use it only in dev mode.

**Comment by SimonSelg** [comment] 2016-06-27 18:10
> redux-freeze doesn't really solve that, does it?

No, it doesn't, but it doesn't have to.

The reason why

```js
shouldComponentUpdate(nextProps) {
  return !this.props.equals(nextProps);
}
````

works is because we never mutate the state (and therefore the props that get passed to the component by `connect`). Because of that, we can easily determine if props have changed by `this.props.equals(nextProps)`, because whenever the state changes, we generate a *new* object, meaning we can just do a shallow equal instead of a full deep equal.

`Immutable.js` is just a library that makes working with immutable data structures easier (and doesn't allow them to be mutated). `redux-freeze` on the other hand is just a store enhancer that throws an error if we mutate the state - its purpose is to warn us if we accidentally mutate the state.

So - for 

```js
shouldComponentUpdate(nextProps) {
  return !this.props.equals(nextProps);
}
````

to work we don't need Immutable.js or redux-freeze at all - they are both useful, but have nothing to do with it directly.

Does that help @mxstbr  and @FezVrasta  ?

**Comment by mxstbr** [comment] 2016-06-27 19:16
Ooh that makes a lot of sense, but what if a specific subpart of the state (selected with reselect) changes? Imagine this state tree:

```JS
const state = {
  something: true,
  somethingElse: {
    something: false,
  },
};
```

Now that gets changed to this via an action:


```JS
const state = {
  something: false,
  somethingElse: {
    something: false,
  },
};
```

Now this check will return true, since the object references aren't the same but the subpart of the state hasn't actually changed, right? So this component would then still rerender, even though it's subpart of the state hasn't changed at all.

```JS
state.somethingElse !== state.somethingElse
```

Does reselect fix this? I.e. if we used `connect` and a `getSomethingElse` selector, does this problem maybe go away?

```JS
shouldComponentUpdate(nextProps) {
  return nextProps !== this.props;
}
// …
connect(createSelector(getSomethingElse(), (somethingElse => { somethingElse })))(Component);
```

**Comment by tzarger** [comment] 2016-06-28 21:19
@mxstbr @SimonSelg if you were going to want to **shouldComponentUpdate** based on the **somethingElse** sub-state, why not create a selector for that part of the state tree? Would that fix your example?

**Comment by mxstbr** [comment] 2016-06-29 10:25
That's exactly my question haha

**Comment by Dattaya** [comment] 2016-08-10 09:52
For those who don't want to have Immutable.js in their project, I'm maintaining a copy of this repository with Imm.js removed: https://github.com/Dattaya/react-boilerplate-object I wasn't hard, just had to delete a bunch of code, as a result the project became 151 lines lighter: https://github.com/Dattaya/react-boilerplate-object/commit/712b0726acca8f0da4a2aa4eb19f9321b35ad6e9

In `App`'s reducer that required changing a state one level deeper I used React immutability helper (https://github.com/Dattaya/react-boilerplate-object/blob/master/app/containers/App/reducer.js#L34):
```js
      return update(state, {
        loading: { $set: true },
        error: { $set: false },
        userData: { repositories: { $set: false } },
      });
```

Of course remember to use pureRender HoC in places that change a lot. You can create your own depending on your project needs, for one of my project I don't need to account for functions in props and state, so I made a custom pureRender component:
```js
import reject       from 'lodash/reject';
import isFunction   from 'lodash/isFunction';
import shallowEqual from 'shallowequal';

/**
 * In this project state is not used, so a comparison between the next state vs. current one is not done
 * @param nextProps
 * @returns {boolean}
 */
function shouldComponentUpdate(nextProps) {
  return !shallowEqual(reject(this.props, isFunction), reject(nextProps, isFunction));
}

export default (component) => {
  component.prototype.shouldComponentUpdate = shouldComponentUpdate;
  return component;
}
```

**Comment by neverfox** [comment] 2016-09-23 18:54
Any consideration for [seamless-immutable](https://github.com/rtfeldman/seamless-immutable) as a middle ground?

**Comment by mxstbr** [comment] 2016-09-23 22:11
> Any consideration for seamless-immutable as a middle ground?

Does that answer the above question? "what if a specific subpart of the state (selected with reselect) does not change?"

**Comment by aminimalanimal** [comment] 2017-03-09 20:08
Out of all the technologies introduced to me by React-Boilerplate, I've found Immutable.js to be the easiest to learn and probably the most secretly helpful. Despite having used JavaScript for years (in jQuery-heavy projects), I still found myself accidentally mutating my state by doing things like:
```
const foo = [];
const bar = foo.push('baz')
```
_Oh, cool. Even though I assigned `foo` to a new `const`, I still mutated it. Ugh._

The only issues I experienced when learning it were caused by a lack of its presence in the majority of the documentation for other features (such as Redux, since React-Boilerplate's documentation for Redux simply points to Redux's own documentation, which doesn't use Immutable), so I had to grasp _what was expected within RB_ and mentally convert from there.
I think that confusion can be solved easily by updating RB's documentation on Redux to explain that Immutable is used within RB by default, and that some mental conversion of Redux's examples is necessary.
I know, I know, there's a separate link for it, but that makes it seem like a separate feature, so a newcomer can easily trip by choosing to copy/paste stuff from Redux's documentation only to hit the error within `selectors.js` as it attempts to convert a normal JS object back to JS.

After you understand what's going on though, it's one of the least complex things to work with in the project, and having standardized methods for manipulating many different types of data structures is extremely nifty.

**Comment by Jamakase** [comment] 2017-09-14 11:28
@mxstbr Does it really worth it having Immutable.js? We now have PureComponent and recompose/pure which use shallowEqual. Isn't it's performance enough?

Also we can use some custom equalityCheck for `defaultMemoize`. In this case refs that will be returned from selector will be the same.

As i see the only benefit here for using Immutable.js is that ref's stay the same and components are not updated and i think this can be solved without immutable.js.

**Comment by dantman** [comment] 2017-09-14 11:37
> @mxstbr Does it really worth it having Immutable.js? We now have PureComponent and recompose/pure which use shallowEqual. Isn't it's performance enough?

PureComponent **is** the reason Immutable.js is used where people use it in react (or use an alternative immutability solution). PureComponent doesn't work if your data is not immutable.

**Comment by blling** [comment] 2018-01-24 16:55
Close this in favor of #2092

**Closed by blling** 2018-01-24 16:55 UTC
Labels: discussion
