### ISSUE TITLE
Dev Branch: Route sagas are injected twice on Reload/init

### ISSUE THREAD

**Issue by raduflp** [react-boilerplate/react-boilerplate#1613] opened 2017-02-25 14:34 UTC
The described issue is only reproducible on the current Dev branch.

On reload (F5), the route sagas are injected twice. As an effect, you get duplicate network calls. 
When moving between paths, it seems to be working correctly.

I'm just starting with this boilerplate, I'll try to look into it myself if I get a chance,

**Comment by Radu-Filip** [comment] 2017-02-25 18:52
Looks like dependencies update broke this in #1501 . Maybe @gihrig or someone else more experienced than myself can look into it.

**Comment by gihrig** [comment] 2017-02-26 17:14
@Radu-Filip Thanks for researching this. 

It's a known issue, corrected in #1301 where react-router-redux was rolled back to 4.0.6. The update to 4.0.7 in #1501 was an error 😞 .

Have you confirmed 4.0.8 no longer has the problem by actual test?

Thanks again for your help. ✨

**Comment by Radu-Filip** [comment] 2017-02-26 17:42
Yes, I've tested it with 4.0.8 and I can't reproduce the issue. Looks like it was an issue with the way History 3.x  works, and that was fixed [here](https://github.com/reactjs/react-router-redux/commit/a2825ac0b8e34662624455ab98e29e2eb27f8096)

**Comment by justingreenberg** [comment] 2017-07-21 07:21
this should be resolved by #1746 — feedback is welcome! thank you!

**Closed by justingreenberg** 2017-07-21 07:21 UTC
