### ISSUE TITLE
Warning: setState(...): Can only update a mounted or mounting component.

### ISSUE THREAD

**Issue by gihrig** [react-boilerplate/react-boilerplate#1505] opened 2017-01-22 07:26 UTC
This appears in Chrome console in dev mode when the "Features" page is opened. I have not determined how to reproduce it reliably, but I have seen it several times while updating deps.

warning.js:36 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the AppWithProgressBar component.

PR at #1553

To reproduce:
Confirm #1501 has merged <--- It has
Checkout latest dev branch
`npm start`
Open in bowser
Click "Features" link

Boilerplate 3.4+ `dev` branch (ad871d7a1b70cec5b365fdc30eb86ee7e189158f)
Node 7.4.0
npm 4.1.1
yarn 0.19.1
Mac OS 10.11.6
Chrome 55.0.2883.95 (64-bit))

**Comment by Trakkasure** [comment] 2017-01-22 19:36
Could have something to do with asynchronous code (promise, generator, or async/await) in your project being run within componentDidMount or componentWillMount.

**Comment by KarandikarMihir** [comment] 2017-01-23 04:37
@gihrig Could this be related to Progress Bar?

**Comment by gihrig** [comment] 2017-01-23 06:53
@KarandikarMihir 

> Please check the code for the AppWithProgressBar component.

That's how I interpret the error message. Also the semi-random nature of the error's appearance suggests that @Trakkasure may be on the right track.

**Comment by KarandikarMihir** [comment] 2017-01-23 10:52
@gihrig  Oh, sorry I didn't read `AppWithProgressBar`. I'll have a look tonight.

**Comment by KarandikarMihir** [comment] 2017-01-23 16:21
A sure-shot way to reproduce this is to select a language from the select box down below.

**Comment by gihrig** [comment] 2017-01-23 19:05
>A sure-shot way to reproduce this is to select a language from the select box down below and navigate to Features page.

Not working for me, but if it works for you that's great!

`npm start`
`localhost:3000` (open dev tools console)
`lang de`
`Features`

Tried several times changing language then changing route between home and features. No errors today...

But, after a build I can reproduce the error reliably, every time I click the Features link.

`npm run build`
`npm start`
`Features`
`Home`
`Features`

I now have 10 instances of the error and never changed language (since the build).

Hope that helps.

**Comment by gihrig** [comment] 2017-01-29 05:10
@KarandikarMihir Any progress on this?

**Comment by KarandikarMihir** [comment] 2017-01-29 10:44
@gihrig No, I'm trying to squeeze some time out for this because it looks like it'll take a few hours if not days to fix this. I have it on my to-do list. Sorry for the delay!

**Comment by gihrig** [comment] 2017-02-01 02:56
@KarandikarMihir I just stumbled on this same error on react-hot-loader [#457 comment](https://github.com/gaearon/react-hot-loader/issues/457#issuecomment-273920552). There's a solution there that might give you a clue.

**Comment by KarandikarMihir** [comment] 2017-02-01 04:39
@gihrig Thanks! It looks like it makes sense.

**Comment by KarandikarMihir** [comment] 2017-02-03 09:11
@gihrig I moved a method that called `setState()` from `componentDidMount()` to `constructor()` as suggested in [#457 comment](https://github.com/gaearon/react-hot-loader/issues/457#issuecomment-273920552). 

I can't reproduce the error `Warning: setState(...): Can only update a mounted or mounting component`. Not sure if it is fixed. I'll create a PR so that everybody can test it.

**Comment by samit4me** [comment] 2017-02-12 04:58
### Steps taken to reproduce problem
1.  `git clone https://github.com/KarandikarMihir/react-boilerplate.git`
1. `git co bfix/progress-state-error`
1. `yarn`
1. `npm start`
1. Open http://localhost:3000/ in Chrome
1. Open devtools
1. Select Network tab in devtools
1. Select GPRS in the throttling dropdown.
1. On the webpage, click the Features button.
1. Then quickly select "de" from the language dropdown in the footer
1. 💥 the error

### Problem
After initial investigations, it looks like the issue has nothing to do with the `withProgressBar()` as I've removed it from the boilerplate and could still replicated the issue, so this problem has probably been around for some time.

I believe this issue exists because the `<Router />` is a child of `<LanguageProvider />`. Therefore, when you select a different language it causes the `<LanguageProvider />` to re-render, which causes `<Router />` to unmount.

Unfortunately, `react-router` calls `setState()` inside of `<Router />.componentWillMount()`, see [L102 of Router.js](https://github.com/ReactTraining/react-router/blob/master/modules/Router.js#L102). Usually this doesn't cause any issues but if you change the language in the middle of a route transition, the `setState()` mentioned above is executed after `<Router />` has been unmounted, which gives the error in question.

### Possible solution
Not sure if it is possible, but if we could move `<LanguageProvider />` to be a child of `<Router />` we may have a better chance of resolving this problem. The current challenge is that the messages are passed into `<LanguageProvider />` as props are hot reloadable.

My initial thoughts are to move these hot messages into the Redux store, but would love to hear other peoples thoughts on this???

**Comment by gretzky** [comment] 2018-02-16 21:46
Closing due to inactivity

**Closed by gretzky** 2018-02-16 21:46 UTC
Labels: PR welcome, bug
