### ISSUE TITLE
pre-commit hook fails on ConEmu console

### ISSUE THREAD

**Issue by josecelano** [react-boilerplate/react-boilerplate#2056] opened 2017-12-08 10:17 UTC
I am using:

* Windows 8.1 pro
* Console: [ConEmu](https://conemu.github.io/)
* Node: v9.2.0
* Npm: 5.5.1

After git commit, pre-commit script fails because there are some errors with lint. If I run it manually (`npm run lint`) it works.

It works using GitBash console.

**Comment by gretzky** [comment] 2017-12-13 22:39
Can you show a stack trace of the errors?

**Comment by sourcesoft** [comment] 2017-12-14 00:11
use `git commit -n -m "message"`

**Comment by avdeev** [comment] 2017-12-18 10:59
`pre-commit` has some issues related with Windows

https://github.com/observing/pre-commit/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+windows

**Comment by mxstbr** [comment] 2017-12-18 11:03
Maybe we should switch to `husky`?

**Comment by avdeev** [comment] 2017-12-18 11:17
@mxstbr  `husky` looks more popular
https://npmcompare.com/compare/husky,pre-commit

I can prepare PR

**Comment by mxstbr** [comment] 2017-12-18 11:23
SGTM

**Comment by josecelano** [comment] 2017-12-18 11:39
Thank you all. I can't reproduce the problem again. I will add more info here if it happens again, although it seems to be a problem with `pre-commit`.

**Comment by avdeev** [comment] 2017-12-18 13:09
@mxstbr Done #2072

Looks good

**Comment by blling** [comment] 2017-12-20 10:10
Switch to husky has done in #2072, thanks @avdeev.  
@josecelano as you comment:
>Thank you all. I can not reproduce the problem again. I will add more info here if it happens again, 
although it seems to be a problem with pre-commit.

I will close this issue, if you find the problem is related to RBP, please re-create a new issue with more error info, thanks.

**Closed by blling** 2017-12-20 10:10 UTC
Labels: waiting-for-response
